# Buildpack API version
api = "0.10"
# WithWindowsBuild = false
# WithLinuxBuild = false

[buildpack]
id = "schematic/base"
version = "0.1.1"
name = "Schematic Base Buildpack"
homepage = "https://github.com/metasync/schematic-buildpacks"

# Targets the buildpack will work with
[[targets]]
os = "linux"
arch = "amd64"

# To be deprecated
[[stacks]]
id = "io.buildpacks.stacks.schematic.base"
