apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-kpack-cluster-stack-pipeline
  namespace: tekton-ci
spec:
  params:
    - name: cluster-stack-name
      description: Name of the kpack ClusterStack to patch
      default: "schematic-base"
    - name: base-image-type
      description: Type of base (run or build) image to patch
      type: string
  tasks:
    - name: patch-kpack-cluster-stack
      taskRef:
        name: patch-kpack-cluster-stack-task
      params:
        - name: cluster-stack-name
          value: "$(params.cluster-stack-name)"
        - name: base-image-type
          value: "$(params.base-image-type)"
