apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-ci-kpack-clusterrole
rules:
  - apiGroups: ["kpack.io"]
    resources: ["images", "clusterstacks"]
    verbs: ["get", "patch"]
