apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: schematic-base
spec:
  serviceAccountRef: 
    name: kpack-sa
    namespace: kpack
  tag: quay.io/metasync/schematic_builder_base:al2023
  stack:
    name: schematic-base
    kind: ClusterStack
  store:
    name: schematic-buildpacks
    kind: ClusterStore
  order:
    - group:
      - id: schematic/base
        # version: "0.1.0"
