apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: dagster-image
  namespace: kpack
spec:
  tag: quay.io/metasync/schematic_dagster:1.10
  # additionalTags:
  #   - quay.io/metasync/schematic_dagster:1.10.1
  serviceAccountName: kpack-sa
  builder:
    name: schematic-base
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/metasync/schematic_dagster.git
      revision: main
      # revision: v0.1.0
      # revision: 3be289517d320a47bb8f359acc1d1daf0829ed0b
  projectDescriptorPath: ./bpproject.toml
  failedBuildHistoryLimit: 3
  successBuildHistoryLimit: 3
  build:
    creationTime: "now"
    env:
      # Update this build-time env variable to force image rebuild
      # Please increment the value by 1 for each force image rebuild
      - name: BP_FORCE_REBUILDS
        value: "0"
    # buildTimeout: 1600
    # resources:
    #   requests:
    #     cpu: "0.25"
    #     memory: "128M"
    #   limits:
    #     cpu: "0.5"
    #     memory: "256M"
    # tolerations:
    #   - key: "image-builder"
    #     operator: "Exists"
    #     effect: "NoSchedule"
    # nodeSelector:
    #   type: infra-node
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: kubernetes.io/infra-nodes
    #               operator: In
    #               values:
    #                 - infra-node-1
    #                 - infra-node-2
