apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: schematic-base
spec:
  id: "io.buildpacks.stacks.schematic"
  buildImage:
    image: "quay.io/metasync/schematic_buildpacks_build_base:al2023-20250207.095709"
  runImage:
    image: "quay.io/metasync/schematic_buildpacks_run_base:al2023-20250207.102720"
