#!/usr/bin/env bash

kubectl apply -f quay_registry_credentials.yaml -n kpack
kubectl apply -f service_account/kpack_sa.yaml -n kpack
kubectl apply -f cluster_store.yaml -n kpack
kubectl apply -f cluster_stacks/schematic_base.yaml -n kpack
kubectl apply -f cluster_builders/schematic_base.yaml -n kpack
