#!/usr/bin/env bash

# Kpack setup
kubectl apply -f quay_registry_credentials.yaml
kubectl apply -f service_account/kpack_sa.yaml
kubectl apply -f cluster_store.yaml -n kpack
kubectl apply -f cluster_stacks/schematic_base.yaml
kubectl apply -f cluster_builders/schematic_base.yaml

# ArgoCD setup
cd argocd; ./setup ; cd ..

# Tekton setup
cd tekton; ./setup; cd ..
