# Buildpacks to include in builder
[[buildpacks]]
id = "schematic/python-uv"
version = "0.1.0"
uri = "../buildpacks/python-uv"

# Order used for detection
[[order]]
  [[order.group]]
  id = "schematic/python-uv"
  # version = "0.1.0"

# Base images used to create the builder
[build]
image = "quay.io/metasync/schematic_buildpacks_build_base:al2023"

[run]
  [[run.images]]
  image = "quay.io/metasync/schematic_buildpacks_run_base:al2023"

# Stack (deprecated) used to create the builder
# [stack]
# id = "io.buildpacks.schematic.stacks.al2023"
# build-image = "quay.io/metasync/schematic_buildpacks_build_base:al2023"
# run-image = "quay.io/metasync/schematic_buildpacks_run_base:al2023"